### ISSUE TITLE
Bot doesn't collect the Nimbus Medals from Time Attack Missions

### ISSUE THREAD

**Issue by NilBarua** [FlashChaser/Open-Source-Battle-Bot#65]
Hi,

I tried to just collect Nimbus Cloud medals from the events and I do the missions like they are asked on the bot, but it doesn't seem to collect the Nimbus Cloud medals. Now I know that this is more a request than a issue seeming this hasn't been in the system or can't be done for some reason.

Is there any way you could implement a code that also does the Time Attack missions that also collects the Nimbus medals. I tried accepting missions but it's still not in my inv. Anyways, thanks guys.

**Comment by PeterPlanlos** [comment]
The requirements for the nimbus cloud medals are different its not a issue from the bot. If i remember right a requirement is to complete the event stage within some time limit the bot has a higher random value to complete the stages and you need some specific characters in your team to aquire most of the nimbus.

At all its not clear for the bot  when it play that stage if you want to collect the nimbus medals or if you just want to complete the stage on normal way. Its needet a new command for the bot to farm that nimbu medals maybe a dev here around can build such a command but i think it will fail because the need of different characters in your team for the different stages.

Hope to make it clear enough why its not working currently
